# Looks like reusable workflows must reside in the .github/workflows folder to be usable.
# Example discussion - https://github.com/actions/runner/issues/1493
name: Deployments Lower - Common Progression

on: 
  workflow_call:
    # inputs:
    #   myENV_NAME:
    #     description: Regions we will be deploying to.
    #     required: true
    #     type: string

jobs:
  
  deploy_dev:
    name: Development
    runs-on: ubuntu-latest
    environment: 'dev'
    steps:
      - name: dev deploy
        run: |
          echo "Hello Developers!"

  deploy_qa:
    name: QA
    runs-on: ubuntu-latest
    environment: 'qa'
    needs: deploy_dev
    steps:
      - name: qa deploy
        run: |
          echo "Hello QA!"